### ISSUE TITLE
Button unclickable, nothing happens

### ISSUE THREAD

**Issue by alphapapa** [fiveNinePlusR/tabist#19] opened 2016-09-25 17:21 UTC
Firefox 48.0
extension just installed from AMO a moment ago

The button on the toolbar does not have hover feedback.  When clicked, nothing happens.

When moved to the menu, the button has hover feedback, but when clicked, nothing happens.

I opened the Browser Console, disabled the extension, and reenabled it.  I saw these messages, but I'm not sure if they're part of the problem:

``````
[Exception... "Component returned failure code: 0x805e0006 [nsIWebNavigation.loadURI]"  nsresult: ```
"0x805e0006 (<unknown>)"  location: "JS frame :: chrome://extensions/content/ext-backgroundPage.js :: build :: line 64"  data: no]: build@chrome://extensions/content/ext-backgroundPage.js:64:5
@chrome://extensions/content/ext-backgroundPage.js:120:3
EventEmitter_emit@resource://devtools/shared/event-emitter.js:163:11
emit@resource://gre/modules/Extension.jsm:229:29
runManifest@resource://gre/modules/Extension.jsm:1352:9
startup/<@resource://gre/modules/Extension.jsm:1424:14

EventEmitter_emit()
event-emitter.js:168
emit()
Extension.jsm:229
runManifest()
Extension.jsm:1352
startup/<()
Extension.jsm:1424
``````

> 1474823902593 addons.webextension.{607e6aa4-8374-4df2-8922-931d1ac961f6}  WARN    Please specify whether you want browser_style or not in your browser_action options.

I don't know what else to do.  This extension looks so useful, but it just doesn't work.  :(

**Comment by fiveNinePlusR** [comment] 2016-09-26 03:35
That's odd... does control+shift+E or command+shift+E bring up the tabist page?  I will check on some things with 48 to see if there is an incompatibility. Can you provide what operating system and what extensions you have enabled?

**Comment by fiveNinePlusR** [comment] 2016-09-26 15:51
I just tried it out on a firefox 48 instance and it worked as expected. There was hover feedback and the shortcut key combination worked and the button worked as expected. Try restarting the browser and seeing if that helps.

**Comment by alphapapa** [comment] 2016-09-26 19:31
I restarted Firefox but it made no difference.

I'm on Ubuntu 14.04.  I use these extensions:
- BetterPrivacy
- Classic Theme Restorer
- Cookie Monster
- DownThemAll!
- FabTabs
- Greasemonkey
- Just Disable Stuff
- Lazarus
- Mozilla Archive Format
- NoScript
- Pentadactyl
- Perspectives
- Pocket
- Reddit Enhancement Suite
- RequestPolicy
- RequestPolicy Sync
- ScrapBook
- SettingSanity
- Stylish
- TabLister
- Tab Mix Plus
- uBlock Origin
- VTzilla

Pentadactyl is obviously an "invasive" extension, but I don't see how it could be causing any problems, since all the other extensions work fine, and I've been using it for many years.

Thanks for your help.  Please let me know what else I can do to help debug it.

**Comment by fiveNinePlusR** [comment] 2016-09-26 20:42
Well, that's a long list of extensions... as a first pass I would try to install it in a fresh profile to see if it's either something in your extensions/some other type of profile corruption or configuration. If it still doesn't work in a fresh profile then it might be an ubuntu bug. If it works in a fresh profile you can switch back to your default profile and disable half of the extensions(if it doesn't work with those extensions disabled you disable the other half if it works with those disabled you can enable some of the disabled extensions to figure out which one it is conflicting with quickly.) to diagnose which one is conflicting with Tabist. My addon doesn't do anything too outlandish so if I had to guess it's an intrusive extension that is conflicting with Tabist(maybe: RequestPolicy, Just Disable Stuff, NoScript, Pentadactyl) I use uBlock origin and betterPrivacy so those are fine. 

To switch to a fresh profile:

On Linux: Open a terminal and run the firefox --no-remote -profilemanager command. typically you only have one "default" profile so just create a temp profile, uncheck use this profile as default and click start firefox. 

If you can figure out what extension it is I can try to figure out why it's conflicting here.

**Comment by alphapapa** [comment] 2016-09-26 23:13
Thanks, I'll let you know what I find out.

**Comment by fiveNinePlusR** [comment] 2016-09-26 23:32
It's caused by RequestPolicy. you can whitelist the app somehow or disable requestPolicy until this bug is resolved somehow: https://bugzilla.mozilla.org/show_bug.cgi?id=1298856

**Comment by alphapapa** [comment] 2016-09-27 01:16
Thanks for finding that.  It seems strange that none of my other extensions have a problem with it.  I guess these new extension APIs are still not well-tested.

**Comment by fiveNinePlusR** [comment] 2016-09-27 01:40
You're welcome. Yeah, the webextension API is where Firefox is moving to with extensions and the original one is being deprecated. Chrome and Firefox are going to support webextensions going forward. 

I added a bug to the RequestPolicyContinued project to see them rectify this issue with webextensions. Let me know if there is anything else I can do. 

Cheers.

**Closed as completed by fiveNinePlusR** 2016-09-27 01:40 UTC

**Comment by alphapapa** [comment] 2016-09-27 01:48
Well, I got it working.  Here's what I did:
1.  I tried to add exceptions to RequestPolicy going by the instructions on that bug report.  I dug the UUID out of the `extensions.json` file and added it as an exception in the RP rules from `about:blank` to both `moz-extension://{607e6aa4-8374-4df2-8922-931d1ac961f6}` and `moz-extension://607e6aa4-8374-4df2-8922-931d1ac961f6`.  But it didn't work.
2.  I removed RequestPolicy and installed RequestPolicy Continued.  It imported the rules from RP.  And now Tabist works.  

I think the rule to add is from `about:blank` (or `about:<path>`, as RPC imported it) to `moz-extension://{607e6aa4-8374-4df2-8922-931d1ac961f6}`.

**Comment by fiveNinePlusR** [comment] 2016-09-27 01:52
Cool, thanks for the follow up!

**Comment by fiveNinePlusR** [comment] 2016-09-27 17:38
Is it possible for you to share a screenshot of your configuration so that I might be able to get this fixed in RequestPolicyContinued?

**Comment by alphapapa** [comment] 2016-09-27 22:27
Sure:
![rpc](https://cloud.githubusercontent.com/assets/601365/18894293/b2dfb19a-84d7-11e6-94e2-78dae50b9d34.png)

**Comment by fiveNinePlusR** [comment] 2016-10-01 20:41
looks like the dev for that addon updated it to fix this issue: 

https://github.com/RequestPolicyContinued/requestpolicy/commit/4d46d25c7851e8881c831934e292ccfa93ba3ce0

https://bugzilla.mozilla.org/show_bug.cgi?id=1298856
